/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.chasen.cabocha;

public class CaboChaJNI {
  public final static native int CABOCHA_EUC_JP_get();
  public final static native int CABOCHA_CP932_get();
  public final static native int CABOCHA_UTF8_get();
  public final static native int CABOCHA_ASCII_get();
  public final static native int CABOCHA_IPA_get();
  public final static native int CABOCHA_JUMAN_get();
  public final static native int CABOCHA_UNIDIC_get();
  public final static native int CABOCHA_FORMAT_TREE_get();
  public final static native int CABOCHA_FORMAT_LATTICE_get();
  public final static native int CABOCHA_FORMAT_TREE_LATTICE_get();
  public final static native int CABOCHA_FORMAT_XML_get();
  public final static native int CABOCHA_FORMAT_CONLL_get();
  public final static native int CABOCHA_FORMAT_NONE_get();
  public final static native int CABOCHA_INPUT_RAW_SENTENCE_get();
  public final static native int CABOCHA_INPUT_POS_get();
  public final static native int CABOCHA_INPUT_CHUNK_get();
  public final static native int CABOCHA_INPUT_SELECTION_get();
  public final static native int CABOCHA_INPUT_DEP_get();
  public final static native int CABOCHA_OUTPUT_RAW_SENTENCE_get();
  public final static native int CABOCHA_OUTPUT_POS_get();
  public final static native int CABOCHA_OUTPUT_CHUNK_get();
  public final static native int CABOCHA_OUTPUT_SELECTION_get();
  public final static native int CABOCHA_OUTPUT_DEP_get();
  public final static native int CABOCHA_TRAIN_NE_get();
  public final static native int CABOCHA_TRAIN_CHUNK_get();
  public final static native int CABOCHA_TRAIN_DEP_get();
  public final static native int Chunk_link_get(long jarg1, Chunk jarg1_);
  public final static native long Chunk_head_pos_get(long jarg1, Chunk jarg1_);
  public final static native long Chunk_func_pos_get(long jarg1, Chunk jarg1_);
  public final static native long Chunk_token_size_get(long jarg1, Chunk jarg1_);
  public final static native long Chunk_token_pos_get(long jarg1, Chunk jarg1_);
  public final static native float Chunk_score_get(long jarg1, Chunk jarg1_);
  public final static native String Chunk_additional_info_get(long jarg1, Chunk jarg1_);
  public final static native int Chunk_feature_list_size_get(long jarg1, Chunk jarg1_);
  public final static native String Chunk_feature_list(long jarg1, Chunk jarg1_, long jarg2);
  public final static native String Token_surface_get(long jarg1, Token jarg1_);
  public final static native String Token_normalized_surface_get(long jarg1, Token jarg1_);
  public final static native String Token_feature_get(long jarg1, Token jarg1_);
  public final static native int Token_feature_list_size_get(long jarg1, Token jarg1_);
  public final static native String Token_ne_get(long jarg1, Token jarg1_);
  public final static native String Token_additional_info_get(long jarg1, Token jarg1_);
  public final static native long Token_chunk_get(long jarg1, Token jarg1_);
  public final static native String Token_feature_list(long jarg1, Token jarg1_, long jarg2);
  public final static native int EUC_JP_get();
  public final static native int CP932_get();
  public final static native int UTF8_get();
  public final static native int ASCII_get();
  public final static native int IPA_get();
  public final static native int JUMAN_get();
  public final static native int UNIDIC_get();
  public final static native int FORMAT_TREE_get();
  public final static native int FORMAT_LATTICE_get();
  public final static native int FORMAT_TREE_LATTICE_get();
  public final static native int FORMAT_XML_get();
  public final static native int FORMAT_CONLL_get();
  public final static native int FORMAT_NONE_get();
  public final static native int INPUT_RAW_SENTENCE_get();
  public final static native int INPUT_POS_get();
  public final static native int INPUT_CHUNK_get();
  public final static native int INPUT_SELECTION_get();
  public final static native int INPUT_DEP_get();
  public final static native int OUTPUT_RAW_SENTENCE_get();
  public final static native int OUTPUT_POS_get();
  public final static native int OUTPUT_CHUNK_get();
  public final static native int OUTPUT_SELECTION_get();
  public final static native int OUTPUT_DEP_get();
  public final static native int TRAIN_NE_get();
  public final static native int TRAIN_CHUNK_get();
  public final static native int TRAIN_DEP_get();
  public final static native void Tree_set_sentence(long jarg1, Tree jarg1_, String jarg2);
  public final static native String Tree_sentence(long jarg1, Tree jarg1_);
  public final static native long Tree_sentence_size(long jarg1, Tree jarg1_);
  public final static native long Tree_chunk(long jarg1, Tree jarg1_, long jarg2);
  public final static native long Tree_token(long jarg1, Tree jarg1_, long jarg2);
  public final static native boolean Tree_read(long jarg1, Tree jarg1_, String jarg2, int jarg3);
  public final static native boolean Tree_empty(long jarg1, Tree jarg1_);
  public final static native void Tree_clear(long jarg1, Tree jarg1_);
  public final static native void Tree_clear_chunk(long jarg1, Tree jarg1_);
  public final static native long Tree_chunk_size(long jarg1, Tree jarg1_);
  public final static native long Tree_token_size(long jarg1, Tree jarg1_);
  public final static native long Tree_size(long jarg1, Tree jarg1_);
  public final static native String Tree_toString(long jarg1, Tree jarg1_, int jarg2);
  public final static native int Tree_charset(long jarg1, Tree jarg1_);
  public final static native void Tree_set_charset(long jarg1, Tree jarg1_, int jarg2);
  public final static native int Tree_posset(long jarg1, Tree jarg1_);
  public final static native void Tree_set_posset(long jarg1, Tree jarg1_, int jarg2);
  public final static native int Tree_output_layer(long jarg1, Tree jarg1_);
  public final static native void Tree_set_output_layer(long jarg1, Tree jarg1_, int jarg2);
  public final static native String Tree_what(long jarg1, Tree jarg1_);
  public final static native long new_Tree();
  public final static native void delete_Tree(long jarg1);
  public final static native long Parser_parse__SWIG_0(long jarg1, Parser jarg1_, String jarg2);
  public final static native String Parser_parseToString(long jarg1, Parser jarg1_, String jarg2);
  public final static native long Parser_parse__SWIG_1(long jarg1, Parser jarg1_, long jarg2, Tree jarg2_);
  public final static native String Parser_what(long jarg1, Parser jarg1_);
  public final static native String Parser_version();
  public final static native void delete_Parser(long jarg1);
  public final static native long new_Parser__SWIG_0(String jarg1);
  public final static native long new_Parser__SWIG_1();
  public final static native String getLastError();
  public final static native boolean runDependencyTraining(String jarg1, String jarg2, String jarg3, int jarg4, int jarg5, double jarg6, int jarg7);
  public final static native boolean runChunkingTraining(String jarg1, String jarg2, String jarg3, int jarg4, int jarg5, double jarg6, int jarg7);
  public final static native boolean runNETraining(String jarg1, String jarg2, String jarg3, int jarg4, int jarg5, double jarg6, int jarg7);
  public final static native String VERSION_get();
}
