/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.chasen.cabocha;

public class Parser {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public Parser(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Parser obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CaboChaJNI.delete_Parser(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Tree parse(String input) {
    long cPtr = CaboChaJNI.Parser_parse__SWIG_0(swigCPtr, this, input);
    return (cPtr == 0) ? null : new Tree(cPtr, false);
  }

  public String parseToString(String input) {
    return CaboChaJNI.Parser_parseToString(swigCPtr, this, input);
  }

  public Tree parse(Tree tree) {
    long cPtr = CaboChaJNI.Parser_parse__SWIG_1(swigCPtr, this, Tree.getCPtr(tree), tree);
    return (cPtr == 0) ? null : new Tree(cPtr, false);
  }

  public String what() {
    return CaboChaJNI.Parser_what(swigCPtr, this);
  }

  public static String version() {
    return CaboChaJNI.Parser_version();
  }

  public Parser(String argc) {
    this(CaboChaJNI.new_Parser__SWIG_0(argc), true);
  }

  public Parser() {
    this(CaboChaJNI.new_Parser__SWIG_1(), true);
  }

}
