/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.chasen.cabocha;

public final class ParserType {
  public final static ParserType TRAIN_NE = new ParserType("TRAIN_NE", CaboChaJNI.TRAIN_NE_get());
  public final static ParserType TRAIN_CHUNK = new ParserType("TRAIN_CHUNK", CaboChaJNI.TRAIN_CHUNK_get());
  public final static ParserType TRAIN_DEP = new ParserType("TRAIN_DEP", CaboChaJNI.TRAIN_DEP_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ParserType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ParserType.class + " with value " + swigValue);
  }

  private ParserType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ParserType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ParserType(String swigName, ParserType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ParserType[] swigValues = { TRAIN_NE, TRAIN_CHUNK, TRAIN_DEP };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

