/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.chasen.cabocha;

class CaboChaJNI {
  public final static native int Chunk_link_get(long jarg1, Chunk jarg1_);
  public final static native int Chunk_head_pos_get(long jarg1, Chunk jarg1_);
  public final static native int Chunk_func_pos_get(long jarg1, Chunk jarg1_);
  public final static native int Chunk_token_size_get(long jarg1, Chunk jarg1_);
  public final static native long Chunk_token_pos_get(long jarg1, Chunk jarg1_);
  public final static native float Chunk_score_get(long jarg1, Chunk jarg1_);
  public final static native int Chunk_feature_list_size_get(long jarg1, Chunk jarg1_);
  public final static native String Chunk_feature_list(long jarg1, Chunk jarg1_, long jarg2);
  public final static native String Token_surface_get(long jarg1, Token jarg1_);
  public final static native String Token_normalized_surface_get(long jarg1, Token jarg1_);
  public final static native String Token_feature_get(long jarg1, Token jarg1_);
  public final static native int Token_feature_list_size_get(long jarg1, Token jarg1_);
  public final static native String Token_ne_get(long jarg1, Token jarg1_);
  public final static native long Token_chunk_get(long jarg1, Token jarg1_);
  public final static native String Token_feature_list(long jarg1, Token jarg1_, long jarg2);
  public final static native void Tree_set_sentence(long jarg1, Tree jarg1_, String jarg2);
  public final static native String Tree_sentence(long jarg1, Tree jarg1_);
  public final static native long Tree_sentence_size(long jarg1, Tree jarg1_);
  public final static native long Tree_chunk(long jarg1, Tree jarg1_, long jarg2);
  public final static native long Tree_token(long jarg1, Tree jarg1_, long jarg2);
  public final static native boolean Tree_read(long jarg1, Tree jarg1_, String jarg2, int jarg3);
  public final static native boolean Tree_empty(long jarg1, Tree jarg1_);
  public final static native void Tree_clear(long jarg1, Tree jarg1_);
  public final static native void Tree_clear_chunk(long jarg1, Tree jarg1_);
  public final static native long Tree_chunk_size(long jarg1, Tree jarg1_);
  public final static native long Tree_token_size(long jarg1, Tree jarg1_);
  public final static native long Tree_size(long jarg1, Tree jarg1_);
  public final static native String Tree_toString(long jarg1, Tree jarg1_, int jarg2);
  public final static native int Tree_charset(long jarg1, Tree jarg1_);
  public final static native void Tree_set_charset(long jarg1, Tree jarg1_, int jarg2);
  public final static native int Tree_posset(long jarg1, Tree jarg1_);
  public final static native void Tree_set_posset(long jarg1, Tree jarg1_, int jarg2);
  public final static native int Tree_output_layer(long jarg1, Tree jarg1_);
  public final static native void Tree_set_output_layer(long jarg1, Tree jarg1_, int jarg2);
  public final static native String Tree_what(long jarg1, Tree jarg1_);
  public final static native long new_Tree();
  public final static native void delete_Tree(long jarg1);
  public final static native long Parser_parse__SWIG_0(long jarg1, Parser jarg1_, String jarg2);
  public final static native String Parser_parseToString(long jarg1, Parser jarg1_, String jarg2);
  public final static native long Parser_parse__SWIG_1(long jarg1, Parser jarg1_, long jarg2, Tree jarg2_);
  public final static native String Parser_what(long jarg1, Parser jarg1_);
  public final static native String Parser_version();
  public final static native void delete_Parser(long jarg1);
  public final static native long new_Parser__SWIG_0(String jarg1);
  public final static native long new_Parser__SWIG_1();
  public final static native String VERSION_get();
}
