/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.chasen.cabocha;

public interface CaboChaConstants {
  public final static int CABOCHA_EUC_JP = CaboChaJNI.CABOCHA_EUC_JP_get();
  public final static int CABOCHA_CP932 = CaboChaJNI.CABOCHA_CP932_get();
  public final static int CABOCHA_UTF8 = CaboChaJNI.CABOCHA_UTF8_get();
  public final static int CABOCHA_ASCII = CaboChaJNI.CABOCHA_ASCII_get();

  public final static int CABOCHA_IPA = CaboChaJNI.CABOCHA_IPA_get();
  public final static int CABOCHA_JUMAN = CaboChaJNI.CABOCHA_JUMAN_get();
  public final static int CABOCHA_UNIDIC = CaboChaJNI.CABOCHA_UNIDIC_get();

  public final static int CABOCHA_FORMAT_TREE = CaboChaJNI.CABOCHA_FORMAT_TREE_get();
  public final static int CABOCHA_FORMAT_LATTICE = CaboChaJNI.CABOCHA_FORMAT_LATTICE_get();
  public final static int CABOCHA_FORMAT_TREE_LATTICE = CaboChaJNI.CABOCHA_FORMAT_TREE_LATTICE_get();
  public final static int CABOCHA_FORMAT_XML = CaboChaJNI.CABOCHA_FORMAT_XML_get();
  public final static int CABOCHA_FORMAT_CONLL = CaboChaJNI.CABOCHA_FORMAT_CONLL_get();
  public final static int CABOCHA_FORMAT_NONE = CaboChaJNI.CABOCHA_FORMAT_NONE_get();

  public final static int CABOCHA_INPUT_RAW_SENTENCE = CaboChaJNI.CABOCHA_INPUT_RAW_SENTENCE_get();
  public final static int CABOCHA_INPUT_POS = CaboChaJNI.CABOCHA_INPUT_POS_get();
  public final static int CABOCHA_INPUT_CHUNK = CaboChaJNI.CABOCHA_INPUT_CHUNK_get();
  public final static int CABOCHA_INPUT_SELECTION = CaboChaJNI.CABOCHA_INPUT_SELECTION_get();
  public final static int CABOCHA_INPUT_DEP = CaboChaJNI.CABOCHA_INPUT_DEP_get();

  public final static int CABOCHA_OUTPUT_RAW_SENTENCE = CaboChaJNI.CABOCHA_OUTPUT_RAW_SENTENCE_get();
  public final static int CABOCHA_OUTPUT_POS = CaboChaJNI.CABOCHA_OUTPUT_POS_get();
  public final static int CABOCHA_OUTPUT_CHUNK = CaboChaJNI.CABOCHA_OUTPUT_CHUNK_get();
  public final static int CABOCHA_OUTPUT_SELECTION = CaboChaJNI.CABOCHA_OUTPUT_SELECTION_get();
  public final static int CABOCHA_OUTPUT_DEP = CaboChaJNI.CABOCHA_OUTPUT_DEP_get();

  public final static int CABOCHA_TRAIN_NE = CaboChaJNI.CABOCHA_TRAIN_NE_get();
  public final static int CABOCHA_TRAIN_CHUNK = CaboChaJNI.CABOCHA_TRAIN_CHUNK_get();
  public final static int CABOCHA_TRAIN_DEP = CaboChaJNI.CABOCHA_TRAIN_DEP_get();

  public final static String VERSION = CaboChaJNI.VERSION_get();
}
