/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.chasen.cabocha;

public class CaboCha implements CaboChaConstants {
  public static String getLastError() {
    return CaboChaJNI.getLastError();
  }

  public static boolean runDependencyTraining(String train_file, String model_file, String prev_model_file, CharsetType charset, PossetType posset, double cost, int freq) {
    return CaboChaJNI.runDependencyTraining(train_file, model_file, prev_model_file, charset.swigValue(), posset.swigValue(), cost, freq);
  }

  public static boolean runChunkingTraining(String train_file, String model_file, String prev_model_file, CharsetType charset, PossetType posset, double cost, int freq) {
    return CaboChaJNI.runChunkingTraining(train_file, model_file, prev_model_file, charset.swigValue(), posset.swigValue(), cost, freq);
  }

  public static boolean runNETraining(String train_file, String model_file, String prev_model_file, CharsetType charset, PossetType posset, double cost, int freq) {
    return CaboChaJNI.runNETraining(train_file, model_file, prev_model_file, charset.swigValue(), posset.swigValue(), cost, freq);
  }

}
