/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.33
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.chasen.cabocha;

public class Chunk {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Chunk(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Chunk obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      throw new UnsupportedOperationException("C++ destructor does not have public access");
    }
    swigCPtr = 0;
  }

  public int getLink() {
    return CaboChaJNI.Chunk_link_get(swigCPtr, this);
  }

  public int getHead_pos() {
    return CaboChaJNI.Chunk_head_pos_get(swigCPtr, this);
  }

  public int getFunc_pos() {
    return CaboChaJNI.Chunk_func_pos_get(swigCPtr, this);
  }

  public int getToken_size() {
    return CaboChaJNI.Chunk_token_size_get(swigCPtr, this);
  }

  public long getToken_pos() {
    return CaboChaJNI.Chunk_token_pos_get(swigCPtr, this);
  }

  public float getScore() {
    return CaboChaJNI.Chunk_score_get(swigCPtr, this);
  }

  public int getFeature_list_size() {
    return CaboChaJNI.Chunk_feature_list_size_get(swigCPtr, this);
  }

  public String feature_list(long i) {
    return CaboChaJNI.Chunk_feature_list(swigCPtr, this, i);
  }

}
