/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.chasen.cabocha;

public final class OutputLayerType {
  public final static OutputLayerType OUTPUT_RAW_SENTENCE = new OutputLayerType("OUTPUT_RAW_SENTENCE");
  public final static OutputLayerType OUTPUT_POS = new OutputLayerType("OUTPUT_POS");
  public final static OutputLayerType OUTPUT_CHUNK = new OutputLayerType("OUTPUT_CHUNK");
  public final static OutputLayerType OUTPUT_SELECTION = new OutputLayerType("OUTPUT_SELECTION");
  public final static OutputLayerType OUTPUT_DEP = new OutputLayerType("OUTPUT_DEP");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static OutputLayerType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + OutputLayerType.class + " with value " + swigValue);
  }

  private OutputLayerType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private OutputLayerType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private OutputLayerType(String swigName, OutputLayerType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static OutputLayerType[] swigValues = { OUTPUT_RAW_SENTENCE, OUTPUT_POS, OUTPUT_CHUNK, OUTPUT_SELECTION, OUTPUT_DEP };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

