/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.chasen.cabocha;

public final class PossetType {
  public final static PossetType IPA = new PossetType("IPA");
  public final static PossetType JUMAN = new PossetType("JUMAN");
  public final static PossetType UNIDIC = new PossetType("UNIDIC");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static PossetType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + PossetType.class + " with value " + swigValue);
  }

  private PossetType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private PossetType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private PossetType(String swigName, PossetType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static PossetType[] swigValues = { IPA, JUMAN, UNIDIC };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

