/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.chasen.cabocha;

public class Tree {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Tree(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Tree obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CaboChaJNI.delete_Tree(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void set_sentence(String sentence) {
    CaboChaJNI.Tree_set_sentence(swigCPtr, this, sentence);
  }

  public String sentence() {
    return CaboChaJNI.Tree_sentence(swigCPtr, this);
  }

  public long sentence_size() {
    return CaboChaJNI.Tree_sentence_size(swigCPtr, this);
  }

  public Chunk chunk(long i) {
    long cPtr = CaboChaJNI.Tree_chunk(swigCPtr, this, i);
    return (cPtr == 0) ? null : new Chunk(cPtr, false);
  }

  public Token token(long i) {
    long cPtr = CaboChaJNI.Tree_token(swigCPtr, this, i);
    return (cPtr == 0) ? null : new Token(cPtr, false);
  }

  public boolean read(String input, InputLayerType input_layer) {
    return CaboChaJNI.Tree_read(swigCPtr, this, input, input_layer.swigValue());
  }

  public boolean empty() {
    return CaboChaJNI.Tree_empty(swigCPtr, this);
  }

  public void clear() {
    CaboChaJNI.Tree_clear(swigCPtr, this);
  }

  public void clear_chunk() {
    CaboChaJNI.Tree_clear_chunk(swigCPtr, this);
  }

  public long chunk_size() {
    return CaboChaJNI.Tree_chunk_size(swigCPtr, this);
  }

  public long token_size() {
    return CaboChaJNI.Tree_token_size(swigCPtr, this);
  }

  public long size() {
    return CaboChaJNI.Tree_size(swigCPtr, this);
  }

  public String toString(FormatType output_format) {
    return CaboChaJNI.Tree_toString(swigCPtr, this, output_format.swigValue());
  }

  public CharsetType charset() {
    return CharsetType.swigToEnum(CaboChaJNI.Tree_charset(swigCPtr, this));
  }

  public void set_charset(CharsetType charset) {
    CaboChaJNI.Tree_set_charset(swigCPtr, this, charset.swigValue());
  }

  public PossetType posset() {
    return PossetType.swigToEnum(CaboChaJNI.Tree_posset(swigCPtr, this));
  }

  public void set_posset(PossetType posset) {
    CaboChaJNI.Tree_set_posset(swigCPtr, this, posset.swigValue());
  }

  public OutputLayerType output_layer() {
    return OutputLayerType.swigToEnum(CaboChaJNI.Tree_output_layer(swigCPtr, this));
  }

  public void set_output_layer(OutputLayerType output_layer) {
    CaboChaJNI.Tree_set_output_layer(swigCPtr, this, output_layer.swigValue());
  }

  public String what() {
    return CaboChaJNI.Tree_what(swigCPtr, this);
  }

  public Tree() {
    this(CaboChaJNI.new_Tree(), true);
  }

}
